In [5]:
'''
DataFrame：基本技巧
数据查看、转置、添加、修改、删除值、对齐、排序

'''

'\nDataFrame：基本技巧\n数据查看、转置、添加、修改、删除值、对齐、排序\n\n'

In [6]:
import numpy as np
import pandas as pd

In [11]:
# 数据查看、转置

df = pd.DataFrame(np.random.rand(16).reshape(8,2)*100,
                  columns=['a','b'])
print(df)

print(df.head(2))

print(df.tail())
    # .head()查看头部数据
    # .tail()查看尾部数据
    # 默认查看5条
print(df.T)
    # .T 转置

           a          b
0  87.968834  38.761132
1  76.914210  15.269435
2  10.444597  54.918969
3  71.224403  56.750032
4  96.956876  73.684766
5   7.598459  24.494477
6  63.852434  89.264928
7  40.406651  33.955708
           a          b
0  87.968834  38.761132
1  76.914210  15.269435
           a          b
3  71.224403  56.750032
4  96.956876  73.684766
5   7.598459  24.494477
6  63.852434  89.264928
7  40.406651  33.955708
           0          1          2          3          4          5  \
a  87.968834  76.914210  10.444597  71.224403  96.956876   7.598459
b  38.761132  15.269435  54.918969  56.750032  73.684766  24.494477

           6          7
a  63.852434  40.406651
b  89.264928  33.955708

In [15]:
# 添加与修改

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   columns = ['a','b','c','d'])
print(df)

df['e']=10
df.loc[4]=22
print(df)
    # 新增行列并赋值

df['e']=20
df[['a','c']]=100
print(df)
    # 索引后直接修改值

           a          b          c          d
0  26.885669  74.787713  68.025471  89.282755
1  17.514965  84.317093  56.132079   8.187009
2  85.188133  39.891642  54.471095  17.423663
3  33.466788  73.917629  65.636159  96.831888
           a          b          c          d   e
0  26.885669  74.787713  68.025471  89.282755  10
1  17.514965  84.317093  56.132079   8.187009  10
2  85.188133  39.891642  54.471095  17.423663  10
3  33.466788  73.917629  65.636159  96.831888  10
4  22.000000  22.000000  22.000000  22.000000  22
     a          b    c          d   e
0  100  74.787713  100  89.282755  20
1  100  84.317093  100   8.187009  20
2  100  39.891642  100  17.423663  20
3  100  73.917629  100  96.831888  20
4  100  22.000000  100  22.000000  20

In [23]:
# 删除  del / drop()

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   columns = ['a','b','c','d'])
print(df)

del df['a']
print(df)
    #del语句  删除列
print('..........')
print(df.drop(0))
print(df.drop([1,2]))
print(df)
    # drop()删除行，inplace=False   删除后生成新的数据，不改变原数据
print('...........................')
print(df.drop(['d'],axis=1))
print(df)
    # drop()删除列，需要加上axis=1,inplace=False   删除后生成新的数据，不改变原数据

           a          b          c          d
0  69.205302   9.119630  69.845609  33.124253
1  81.624786  13.326660   6.950924  48.370299
2  71.802847   1.871100  62.558774  49.672200
3  85.475816  64.400677   6.542419  12.039090
           b          c          d
0   9.119630  69.845609  33.124253
1  13.326660   6.950924  48.370299
2   1.871100  62.558774  49.672200
3  64.400677   6.542419  12.039090
..........
           b          c          d
1  13.326660   6.950924  48.370299
2   1.871100  62.558774  49.672200
3  64.400677   6.542419  12.039090
           b          c          d
0   9.119630  69.845609  33.124253
3  64.400677   6.542419  12.039090
           b          c          d
0   9.119630  69.845609  33.124253
1  13.326660   6.950924  48.370299
2   1.871100  62.558774  49.672200
3  64.400677   6.542419  12.039090
...........................
           b          c
0   9.119630  69.845609
1  13.326660   6.950924
2   1.871100  62.558774
3  64.400677   6.542419
           b          c          d
0   9.119630  69.845609  33.124253
1  13.326660   6.950924  48.370299
2   1.871100  62.558774  49.672200
3  64.400677   6.542419  12.039090

In [26]:
# 对齐

df1 = pd.DataFrame(np.random.rand(10,4),columns=['a','b','c','d'])
df2 = pd.DataFrame(np.random.rand(7,3),columns =['a','b','c'])

print(df1)
print(df2)
print(df1+df2)
    # DataFrame 对象之间的数据自动按照列和索引（行标签）对齐

          a         b         c         d
0  0.420834  0.472741  0.032427  0.477060
1  0.617744  0.500621  0.387309  0.833420
2  0.425563  0.087564  0.636439  0.356740
3  0.849394  0.827408  0.109191  0.030725
4  0.246663  0.172057  0.696354  0.359824
5  0.406514  0.542650  0.155668  0.388881
6  0.220678  0.483627  0.769561  0.021932
7  0.042819  0.309655  0.090541  0.472865
8  0.362334  0.930572  0.693601  0.036990
9  0.067822  0.262187  0.415802  0.165504
          a         b         c
0  0.001626  0.469472  0.305852
1  0.874845  0.192312  0.197897
2  0.625546  0.817770  0.045191
3  0.596347  0.263901  0.959151
4  0.493580  0.195693  0.524304
5  0.887018  0.959827  0.050228
6  0.501260  0.596514  0.325542
          a         b         c   d
0  0.422460  0.942213  0.338279 NaN
1  1.492589  0.692933  0.585206 NaN
2  1.051109  0.905334  0.681630 NaN
3  1.445741  1.091309  1.068342 NaN
4  0.740243  0.367750  1.220658 NaN
5  1.293533  1.502478  0.205895 NaN
6  0.721938  1.080142  1.095103 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN

In [39]:
# 排序1 
#      按值排序.sort_values
#      同样适用于Series
df1 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                  columns=['a','b','c','d'])
print(df1)

print(df1.sort_values(['a'],ascending=True))    # a列升序排列
print(df1.sort_values(['a'],ascending=False))    # a列降序排列
    # ascending参数，设置升序降序，默认升序
    #单列排序
print('.......fengexian...............................................')

df2 = pd.DataFrame({'a':[1,1,1,1,2,2,2,2],
                  'b':list(range(8)),
                  'c':list(range(8,0,-1))})
print(df2)
print('.......................................')
print(df2.sort_values(['a','c']))
    # 多列排序，按列顺序排序

           a          b          c          d
0  84.935582  13.062117  33.484826  67.868208
1  36.139165  44.624554  24.052583  47.744041
2  68.627250  25.107125  90.147508   7.380039
3  21.724357  41.597380  99.129459  26.927041
           a          b          c          d
3  21.724357  41.597380  99.129459  26.927041
1  36.139165  44.624554  24.052583  47.744041
2  68.627250  25.107125  90.147508   7.380039
0  84.935582  13.062117  33.484826  67.868208
           a          b          c          d
0  84.935582  13.062117  33.484826  67.868208
2  68.627250  25.107125  90.147508   7.380039
1  36.139165  44.624554  24.052583  47.744041
3  21.724357  41.597380  99.129459  26.927041
.......fengexian...............................................
   a  b  c
0  1  0  8
1  1  1  7
2  1  2  6
3  1  3  5
4  2  4  4
5  2  5  3
6  2  6  2
7  2  7  1
.......................................
   a  b  c
3  1  3  5
2  1  2  6
1  1  1  7
0  1  0  8
7  2  7  1
6  2  6  2
5  2  5  3
4  2  4  4

In [43]:
# 排序2 
#      索引排序 .sort_index
df1 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                  index = [5,4,3,2],
                   columns = ['a','b','c','d'])
print(df1)
print(df1.sort_index())
    #按照index排序
df2 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                  index = ['h','s','x','g'],
                   columns = ['a','b','c','d'])
print(df2)
print(df2.sort_index())
    #按照index排序
    #默认ascending =True 升序，inplace =False

           a          b          c          d
5  53.278393  43.643488  27.603664  35.856563
4  78.928314  53.604367  16.328360  93.873245
3   2.964478  95.530824   9.495479   6.031295
2  31.313869   6.589817  20.994400  16.454904
           a          b          c          d
2  31.313869   6.589817  20.994400  16.454904
3   2.964478  95.530824   9.495479   6.031295
4  78.928314  53.604367  16.328360  93.873245
5  53.278393  43.643488  27.603664  35.856563
           a          b          c          d
h  13.666955  18.465971  13.507700  97.485029
s  30.879892  85.495193  96.341031  40.327608
x  91.262366  64.379895  80.768119  12.596141
g  84.404321  19.166550  72.561211  42.693516
           a          b          c          d
g  84.404321  19.166550  72.561211  42.693516
h  13.666955  18.465971  13.507700  97.485029
s  30.879892  85.495193  96.341031  40.327608
x  91.262366  64.379895  80.768119  12.596141

In [61]:
#作业1：创建一个3*3，值在0-100区间随机值的Dataframe（如图），分别按照index和第二列值大小，降序排序

df =pd.DataFrame(np.random.rand(9).reshape(3,3)*100,
                index=['b','a','c'],
                columns=['v1','v2','v3'])
print(df)

print(df.sort_index(ascending=False))
print(df.sort_values(['v2'],ascending=False))

          v1         v2         v3
b  74.215084  62.302571  84.162565
a  47.890770  12.983459  30.244245
c  27.371768   6.096415  63.240893
          v1         v2         v3
c  27.371768   6.096415  63.240893
b  74.215084  62.302571  84.162565
a  47.890770  12.983459  30.244245
          v1         v2         v3
b  74.215084  62.302571  84.162565
a  47.890770  12.983459  30.244245
c  27.371768   6.096415  63.240893

In [56]:
#作业2：创建一个5*2，值在0-100区间随机值的Dataframe（如图）df1，通过修改得到df2

df = pd.DataFrame(np.random.rand(10).reshape(5,2)*100,
                 index=['a','b','c','d','e'],
                 columns=['v1','v2'])
print(df)

df2 = df.drop(['e'])
print(df2)

df3= df2.T
print(df3)

          v1         v2
a  66.479148  69.713248
b  71.002434  70.903035
c  50.138043  81.605960
d  63.548141   5.700541
e  36.794909  66.525602
          v1         v2
a  66.479148  69.713248
b  71.002434  70.903035
c  50.138043  81.605960
d  63.548141   5.700541
            a          b          c          d
v1  66.479148  71.002434  50.138043  63.548141
v2  69.713248  70.903035  81.605960   5.700541